scene.onOverlapTile(SpriteKind.Player, sprites.castle.saplingPine, function (sprite, location) {
    info.changeScoreBy(10)
    tiles.setTilemap(tilemap`level3`)
    mySprite.setPosition(29, 28)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.shrub, function (sprite, location) {
    info.changeScoreBy(10)
    tiles.setTilemap(tilemap`level4`)
    mySprite.setPosition(29, 28)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava1, function (sprite, location) {
    info.changeLifeBy(-1)
    info.changeScoreBy(-5)
    mySprite.setPosition(29, 28)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.saplingOak, function (sprite, location) {
    tiles.setTilemap(tilemap`level1`)
    mySprite.setPosition(29, 28)
    info.changeScoreBy(10)
})
let mySprite: Sprite = null
scene.setBackgroundColor(15)
tiles.setTilemap(tilemap`level2`)
mySprite = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
mySprite.setPosition(29, 28)
scene.cameraFollowSprite(mySprite)
info.setLife(3)
info.setScore(0)
